### ISSUE TITLE
Beelzeus of the Diabolic Dragons

### ISSUE THREAD

**Issue by FoxtochopKun** [Team13fr/IgnisMulti#2]
Thanks for the translation! But there is a little thing wrong. It is not specified how many Cantantes de Oscuridad (Dark tuner monsters) are needed. It only reads "Cantante de OSCURIDAD" when it should read "1 Cantante de OSCURIDAD".

Just trying to get the most perfect translation for this project. Thanks for the hard work!

**Comment by LucienAclantis** [comment]
Fix in the next updates, the problem was on the Yugipedia page of the card 
https://yugipedia.com/wiki/Beelzeus_of_the_Diabolic_Dragons
