### ISSUE TITLE
German language contains Spanish texts

### ISSUE THREAD

**Issue by Radiant-Xyz** [Team13fr/IgnisMulti#5]
- Eria the Water Charmer [Passcode: 74364659]
- Scrap Recycler [Passcode: 04334811]

**Comment by LucienAclantis** [comment]
Fix :white_check_mark: update at 15/11/2020 23h15

This is an error that comes from the site where we retrieve the card information:
https://yugipedia.com/

I just corrected, I invite you if you find another error to correct directly on the site it works like a Wiki page
Thank you for your report
