### ISSUE TITLE
Remove MediaWiki Code

### ISSUE THREAD

**Issue by Radiant-Xyz** [Team13fr/IgnisMulti#6]
Can you add a filter to remove MediaWiki comments from card names? ~~The lore text doesn't seem to be affected.~~ Appearantly the lore text's formatting code is not removed as well. Some cards (normal monster cards) are formatted in italics and the ' which was used for that is also in the database file. The comment is correctly removed though, but leaves a trailing space.

Example: [Ghoul with an Appetite (95265975)](https://yugipedia.com/wiki/Ghoul_with_an_Appetite) in fr, de, it & es

See also: [MediaWiki Help:Comment tags](https://meta.wikimedia.org/wiki/Help:Comment_tags)

**Comment by bthidev** [comment]
yes tag was only removed on the text of the cards, i think the probleme is fixed

**Comment by Radiant-Xyz** [comment]
I've just tested the new database from f36aeb7 (under the assumption it already includes the fix) and noticed that the German translation is now missing and the English text is displayed instead. Also, you only spoke about the tag in your response. Do you intend to keep the wiki code for italics in the card's text? It does look like quote symbols, but they are not supposed to be some. I'll leave the decision to you, but I wanted to point that out in case you didn't notice my comment about it.

**Comment by bthidev** [comment]
the text of should come back to the next update, do you have example of card with italic text? on "Ghoul with an Appetite" I do not see italic

**Comment by Radiant-Xyz** [comment]
You can see the italics here in the "lore" column. Portuguese isn't in italics, but all of the three above are.
![image](https://user-images.githubusercontent.com/2036401/112511124-64c05500-8d92-11eb-8f89-af65e86200a3.png)

Italics in wiki text are done with two single quotes as seen here:
![image](https://user-images.githubusercontent.com/2036401/112511433-b4068580-8d92-11eb-84b7-f27a771b0bdc.png)

Here's the French card text in-game containing the wiki text:
![image](https://user-images.githubusercontent.com/2036401/112512218-75bd9600-8d93-11eb-941c-14bafcd7c1ce.png)

**Comment by bthidev** [comment]
thanks for the info, I'll look into it later

**Comment by Radiant-Xyz** [comment]
In f002afe all wiki text seems to be properly removed. The only thing that's left it the trailing space at the end, but that's not visible in-game, so this isn't an issue. You could add a trim if you wanted, but otherwise this seems to be resolved. Thanks for your work!

**Comment by bthidev** [comment]
Thanks for your feedback, I will add the trim at the beginning of the week

**Comment by Radiant-Xyz** [comment]
As of 1178358, the trimming seems to be already in place and works just fine. I'll go ahead and close this issue. Thank you @speedi57 for looking into everything I've mentioned! 😄
