### ISSUE TITLE
I would like to help

### ISSUE THREAD

**Issue by Termita** [Team13fr/IgnisMulti#8]
Hello, I belong to the Latino community and I would like to support the project. I have previously worked on the Spanish translation of the CBD since Percy started the project. I represent YGOPro Phoenix, which was the official translation at the time but the project was stopped. If you allow me I can support you, I see some things and details in which I can help you.

**Comment by LucienAclantis** [comment]
IgnisMulti use [https://yugipedia.com/](https://yugipedia.com/) DB for translation you can help directly with the community in this website 👍🏽

**Comment by Termita** [comment]
Excelente, mirare la comunidad. Le paso el string en español actualizado al modelo ignis en ingles. Porque estaba desactualizado y da unos errores en los duelos. Esta completo tanto para pc como para Movil.

https://www.mediafire.com/file/q67nmseeazp9w3s/strings.conf/file

**Comment by Termita** [comment]
Me puede dar una breve orientación de como empesar a contribuir con la Yugipedia? Ya me registre pero no veo como hacerlo.

**Comment by LucienAclantis** [comment]
Tiene une button "Edit" arriba à la derecha de la pagina que quiere modificar, después tiene que modificar la  parte "es_name" y "es_lore" para traducir en español por ejemplo.
Utilice solo la traducción oficial de "[https://www.db.yugioh-card.com/yugiohdb/](https://www.db.yugioh-card.com/yugiohdb/)"
Puede encontrar la mayoría de la veces en la pagina Yugipedia un link con la pagina de la traduction official si ay una.
